---
- hosts: all
  become: yes
  tasks:
  - name: install tomcat9 on ubunt
    ansible.builtin.apt:
      update_cache: yes
      name: tomcat9
      state: present
  - name: install git
    ansible.builtin.apt:
      name: git
      state: present
  - name: install tree on ubunt
    ansible.builtin.apt:
      name: tree
      state: present
         



    


